// <auto-generated />
using System;
using ASPCRUDAssignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPCRUDAssignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPCRUDAssignment.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Bashiir Abshir Ali",
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 79.99m,
                            ProductName = "Wireless Headphones",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Maaido Abdi Said",
                            OrderDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 149.95m,
                            ProductName = "Mechanical Keyboard",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Aniso Farah Jama",
                            OrderDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 34.50m,
                            ProductName = "USB-C Hub",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Mohamed Ali Nur",
                            OrderDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 59.99m,
                            ProductName = "Laptop Stand",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "Abdirahman Abdi Farah",
                            OrderDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 89.00m,
                            ProductName = "Webcam HD",
                            Quantity = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
